# Copyright 2008 Harish Krishnaswamy
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
require 'gwt-blocks-buildr'

desc 'The GWT-Blocks project'
define 'gwt-blocks' do

  init_gwt_project

  build_gwt_module
  
  help do
    puts '-----------------------------------------------------------------------'
  end

end
